CleanupSliceJobs: true

Services:
  RavenDB:
    DiscoveryName: ravendb
    DatabaseName: WePrint_Testing

  RabbitMQ:
    DiscoveryName: rabbitmq
    Username: user
    Password: password
    Queue: Slicer
