name: $(Year:yyyy).$(Month).$(DayOfMonth).$(BuildID)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- script: dotnet publish --configuration $(buildConfiguration) /p:Version=$(Build.BuildNumber)
  displayName: 'Build and Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'WePrint/bin/Release/netcoreapp3.0/publish'
    ArtifactName: 'WePrint.$(Build.BuildNumber).zip'
    publishLocation: 'Container'