trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish --configuration $(buildConfiguration)
  displayName: 'dotnet publish $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'WePrint/bin/Release/netcoreapp3.0/publish'
    ArtifactName: 'WePrint.zip'
    publishLocation: 'Container'