Logging:
  LogLevel:
    Default: Debug
    Microsoft: Information
    System: Information

IdentityServer:
  Key:
    Type: Development

Services:
  RavenDB:
    HostOverride:
      - localhost
    DatabaseName: WePrint_Testing

  RabbitMQ:
    HostOverride: 
      - localhost
    Queue: Slicer_Testing
