Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information

IdentityServer:
  Clients:
    WePrint:
      Profile: IdentityServerSPA
  Key:
    Type: Development # THIS IS BAD AND ADAM SHOULD FIX THIS

Services:
  RavenDB:
    DiscoveryName: ravendb
    DatabaseName: WePrint
    CertFilePath: ""
    CertPassword: ""

  RabbitMQ:
    DiscoveryName: rabbitmq
    Username: user
    Password: password
    Queue: Slicer

AllowedHosts: "*"

FileUploads:
  MaxSizeInMegabytes: 100
  AllowedExtensions:
   - .stl
   - .3mf