Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information

Services:
  RavenDB:
    DiscoveryName: ravendb
    DatabaseName: WePrint
    CertFilePath: ""
    CertPassword: ""

  RabbitMQ:
    Queue: AFineQueue
    DiscoveryName: rabbitmq

AllowedHosts: "*"