version: '3.7'
services:
  weprint:
    image: ${DOCKER_REGISTRY-}weprint/weprint:dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8000:80
    networks:
      - default

  ravendb:
    container_name: ravendb
    networks:
      - default
    environment:
      RAVEN_Setup_Mode: None
      RAVEN_Security_UnsecuredAccessAllowed: PrivateNetwork
      RAVEN_License_Eula_Accepted: "true"
    image: ravendb/ravendb
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
        
      - target: 38888
        published: 38888
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - raven-data:/opt/RavenDB/Server/RavenData
      
networks:
  default:

volumes:
  raven-data: