version: '3.7'
services:
  weprint:
    image: ${DOCKER_REGISTRY-}weprint/weprint:dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8000:80
    networks:
      - default
    depends_on:
      - ravendb

  weprint-slicer:
    image: ${DOCKER_REGISTRY-}weprint/weprint-slicer:dev
    networks:
      - default
    command: Config.yml Config.Development.yml

  rabbitmq:
    container_name: rabbitmq
    networks:
      - default
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    image: rabbitmq:3-management
    ports:
      - target: 4369
        published: 4369
        protocol: tcp
        mode: host
        
      - target: 5671
        published: 5671
        protocol: tcp
        mode: host
        
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
        
      - target: 15671
        published: 15671
        protocol: tcp
        mode: host
        
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
        
      - target: 25672
        published: 25672
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      replicas: 1

  ravendb:
    container_name: ravendb
    networks:
      - default
    environment:
      RAVEN_Setup_Mode: None
      RAVEN_Security_UnsecuredAccessAllowed: PrivateNetwork
      RAVEN_License_Eula_Accepted: "true"
    image: ravendb/ravendb
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
        
      - target: 38888
        published: 38888
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
    volumes:
      - raven-data:/opt/RavenDB/Server/RavenData
      
networks:
  default:

volumes:
  raven-data: