version: '3.7'
services:
  weprint:
    image: ${DOCKER_REGISTRY-}weprint/weprint:dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8000:80
    networks:
      - default
      
networks:
  default: