version: '3.7'
services:
  weprint:
    image: ${DOCKER_REGISTRY-}weprint/weprint:${BUILD_BUILDNUMBER:-latest}
    build:
      context: ../src
      dockerfile: WePrint/Dockerfile
    depends_on:
      - ravendb
  
  ravendb:
    image: ravendb/ravendb
    ports:
      - 9090:8080
      - 38888:38888
    volumes:
      - raven-data:/opt/RavenDB/Server/RavenData

#  rabbitmq:
#    image: rabbitmq/rabbitmq:management
#    ports:
#      - 15672:15672

volumes:
  raven-data:
