version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    networks:
      - raven
      - rabbit
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    image: rabbitmq:3-management
    ports:
      - target: 4369
        published: 4369
        protocol: tcp
        mode: host
        
      - target: 5671
        published: 5671
        protocol: tcp
        mode: host
        
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
        
      - target: 15671
        published: 15671
        protocol: tcp
        mode: host
        
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
        
      - target: 25672
        published: 25672
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      replicas: 1

networks:
  rabbit:
    external: true
  raven:
    external: true