version: '3.7'

services:
  ravendb:
    container_name: ravendb
    networks:
      - raven
    environment:
      RAVEN_Setup_Mode: None
      RAVEN_Security_UnsecuredAccessAllowed: PrivateNetwork
      RAVEN_License_Eula_Accepted: "true"
    image: ravendb/ravendb
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
        
      - target: 38888
        published: 38888
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      replicas: 5
    volumes:
      - raven-data:/opt/RavenDB/Server/RavenData

volumes:
  raven-data:

networks:
  raven:
    external: true