name: $(Year:yyyy).$(Month).$(DayOfMonth).$(BuildID)-dev

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'adam8797/weprint'
    command: 'build'
    Dockerfile: './src/WePrint/Dockerfile'
    buildContext: './src/'
    tags: |
      $(Build.BuildNumber)
      develop
    arguments: '--build-arg app_version=$(Build.BuildNumber) --build-arg configuration=$(buildConfiguration)'

- task: Docker@2
  displayName: Push Image to DockerHub
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'adam8797/weprint'
    command: 'push'
    tags: |
      $(Build.BuildNumber)
      develop