name: $(Year:yyyy).$(Month).$(DayOfMonth).$(BuildID)-dev

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerComposeFile: 'docker-compose.yml'
    additionalDockerComposeFiles: 'docker-compose.test.yml'
    qualifyImageNames: false
    action: 'Build services'
    arguments: '--build-arg app_version=$(Build.BuildNumber) --build-arg configuration=$(buildConfiguration)'
    requireAdditionalDockerComposeFiles: true
    currentWorkingDirectory: './docker'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerComposeFile: 'docker-compose.yml'
    additionalDockerComposeFiles: 'docker-compose.test.yml'
    qualifyImageNames: false
    action: 'Push services'
    arguments: '--build-arg app_version=$(Build.BuildNumber) --build-arg configuration=$(buildConfiguration)'
    requireAdditionalDockerComposeFiles: true
    currentWorkingDirectory: './docker'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerComposeFile: 'docker-compose.yml'
    additionalDockerComposeFiles: 'docker-compose.test.yml'
    qualifyImageNames: false
    action: 'Combine configuration'
    outputDockerComposeFile: '$(Build.StagingDirectory)/docker-compose.yml'
    requireAdditionalDockerComposeFiles: true
    currentWorkingDirectory: './docker'