name: $(Year:yyyy).$(Month).$(DayOfMonth).$(BuildID)-dev

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'
  primaryCompose: './docker/docker-compose.yml'
  altCompose: 'docker-compose.test.yml'

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerComposeFile: $(primaryCompose)
    additionalDockerComposeFiles: $(altCompose)
    qualifyImageNames: false
    action: 'Build services'
    arguments: '--build-arg app_version=$(Build.BuildNumber) --build-arg configuration=$(buildConfiguration)'
    requireAdditionalDockerComposeFiles: true

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerComposeFile: $(primaryCompose)
    additionalDockerComposeFiles: $(altCompose)
    qualifyImageNames: false
    action: 'Push services'
    requireAdditionalDockerComposeFiles: true

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    dockerComposeFile: $(primaryCompose)
    additionalDockerComposeFiles: $(altCompose)
    qualifyImageNames: false
    action: 'Combine configuration'
    outputDockerComposeFile: '$(Build.StagingDirectory)/docker-compose.yml'
    requireAdditionalDockerComposeFiles: true