name: $(Year:yyyy).$(Month).$(DayOfMonth).$(BuildID)

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

- task: Docker@2
  displayName: Build Docker Image
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'adam8797/weprint'
    command: 'build'
    Dockerfile: './src/WePrint/Dockerfile'
    buildContext: './src/'
    tags: |
      $(Build.BuildNumber)
      latest
    arguments: '--build-arg app_version=$(Build.BuildNumber)'

- task: Docker@2
  displayName: Push Image to DockerHub
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'adam8797/weprint'
    command: 'push'
    tags: |
      $(Build.BuildNumber)
      latest